/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_naver_mei_sdk_gif_LZWEncoder */

#ifndef _Included_com_naver_mei_sdk_core_gif_encoder__NativeLZWEncoder
#define _Included_com_naver_mei_sdk_core_gif_encoder__NativeLZWEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LZWEncoder
 * Method:    compress
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_naver_mei_sdk_core_gif_encoder_NativeLZWEncoder_compress
  (JNIEnv * env, jclass, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
